package com.docflow.reports;

import com.docflow.reports.dto.DynamicReportRequest;
import com.docflow.reports.service.DynamicReportBuilder;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.Mockito;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.http.MediaType;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.test.web.servlet.MockMvc;
import org.springframework.test.web.servlet.MvcResult;
import org.springframework.boot.test.mock.mockito.SpyBean;

import java.util.LinkedHashMap;
import java.util.Map;

import org.hamcrest.Matchers;

import static org.assertj.core.api.Assertions.assertThat;
import static org.mockito.ArgumentMatchers.any;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.post;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.jsonPath;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;

@SpringBootTest(properties = {
        "spring.datasource.url=jdbc:h2:mem:reports_e2e;MODE=Oracle;DB_CLOSE_DELAY=-1",
        "spring.datasource.driverClassName=org.h2.Driver",
        "spring.datasource.username=sa",
        "spring.datasource.password=",
        "spring.liquibase.enabled=false",
        "spring.flyway.enabled=false",
        "spring.jpa.hibernate.ddl-auto=none"
})
@AutoConfigureMockMvc
class DynamicReportEndToEndTest {

    @Autowired
    MockMvc mockMvc;

    @Autowired
    JdbcTemplate jdbcTemplate;

    @Autowired
    ObjectMapper objectMapper;

    @SpyBean
    DynamicReportBuilder reportBuilder;

    @BeforeEach
    void setup() {
        jdbcTemplate.execute("CREATE TABLE IF NOT EXISTS user_data (entity_id VARCHAR(64), column_key VARCHAR(100), column_value VARCHAR(255))");
        jdbcTemplate.execute("CREATE TABLE IF NOT EXISTS loan_data (entity_id VARCHAR(64), column_key VARCHAR(100), column_value VARCHAR(255))");
        jdbcTemplate.execute("CREATE TABLE IF NOT EXISTS report_templates (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name VARCHAR(255) NOT NULL, description VARCHAR(4000), config_json CLOB, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL)");

        jdbcTemplate.execute("DELETE FROM user_data");
        jdbcTemplate.execute("DELETE FROM loan_data");
        jdbcTemplate.execute("DELETE FROM report_templates");

        jdbcTemplate.update("INSERT INTO loan_data (entity_id, column_key, column_value) VALUES (?,?,?)", "1", "status", "OPEN");
        jdbcTemplate.update("INSERT INTO loan_data (entity_id, column_key, column_value) VALUES (?,?,?)", "1", "loan_end_date", "2025-12-31");
        jdbcTemplate.update("INSERT INTO loan_data (entity_id, column_key, column_value) VALUES (?,?,?)", "1", "user_id", "U1");

        jdbcTemplate.update("INSERT INTO user_data (entity_id, column_key, column_value) VALUES (?,?,?)", "U1", "username", "Samson");
        jdbcTemplate.update("INSERT INTO user_data (entity_id, column_key, column_value) VALUES (?,?,?)", "U1", "phone_no", "9876543210");
    }

    @Test
    void endToEndReportFlow() throws Exception {
        Mockito.reset(reportBuilder);
        Mockito.doAnswer(invocation -> {
            DynamicReportBuilder.BuiltReport built = (DynamicReportBuilder.BuiltReport) invocation.callRealMethod();
            System.out.println("Generated SQL: " + built.sql());
            return built;
        }).when(reportBuilder).build(any(DynamicReportRequest.class));

        mockMvc.perform(get("/api/reports/meta").param("entity", "loan_data"))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.entity").value("loan_data"))
                .andExpect(jsonPath("$.availableKeys").isArray())
                .andExpect(jsonPath("$.availableKeys").value(Matchers.hasItems("loan_end_date", "status", "user_id")))
                .andExpect(jsonPath("$.relationships[0].to").value("user_data"))
                .andExpect(jsonPath("$.relationships[0].via").value("user_id"));

        String reportRequest = """
                {
                  \"baseEntity\": \"loan_data\",
                  \"columns\": [\"loan_end_date\", \"status\", \"user_data.username\", \"user_data.phone_no\"],
                  \"filters\": [
                    {"key": "status", "op": "=", "value": "OPEN"}
                  ],
                  \"joins\": [
                    {"rightEntity": \"user_data\", "on": \"user_data.entity_id=loan_data.user_id\"}
                  ]
                }
                """;

        String templatePayload = """
                {
                  \"name\": \"Open Loans\",
                  \"request\": %s
                }
                """.formatted(reportRequest);

        MvcResult saveResult = mockMvc.perform(post("/api/reports/templates")
                        .contentType(MediaType.APPLICATION_JSON)
                        .header("X-USER-ID", "tester")
                        .content(templatePayload))
                .andExpect(status().isCreated())
                .andExpect(jsonPath("$.id").isNumber())
                .andExpect(jsonPath("$.name").value("Open Loans"))
                .andReturn();

        long templateId = objectMapper.readTree(saveResult.getResponse().getContentAsString()).get("id").asLong();
        assertThat(templateId).isPositive();

        mockMvc.perform(get("/api/reports/templates"))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.templates[0].id").value(templateId))
                .andExpect(jsonPath("$.templates[0].name").value("Open Loans"))
                .andExpect(jsonPath("$.templates[0].request.baseEntity").value("loan_data"));

        MvcResult runResult = mockMvc.perform(post("/api/reports/run")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(reportRequest))
                .andExpect(status().isOk())
                .andReturn();

        JsonNode responseJson = objectMapper.readTree(runResult.getResponse().getContentAsString());
        assertThat(responseJson.get("rows")).isNotNull();
        assertThat(responseJson.get("rows").isArray()).isTrue();
        assertThat(responseJson.get("rows").size()).isGreaterThanOrEqualTo(1);

        Map<String, String> displayToActual = new LinkedHashMap<>();
        for (JsonNode columnNode : responseJson.get("columns")) {
            String actualName = columnNode.asText();
            if ("entity_id".equals(actualName)) {
                continue;
            }
            String displayName = actualName.contains(".") ? actualName.substring(actualName.indexOf('.') + 1) : actualName;
            displayToActual.put(displayName, actualName);
        }

        assertThat(displayToActual.keySet()).containsExactly("loan_end_date", "status", "username", "phone_no");

        JsonNode firstRow = responseJson.get("rows").get(0);
        assertThat(firstRow.get(displayToActual.get("loan_end_date")).asText()).isEqualTo("2025-12-31");
        assertThat(firstRow.get(displayToActual.get("status")).asText()).isEqualTo("OPEN");
        assertThat(firstRow.get(displayToActual.get("username")).asText()).isEqualTo("Samson");
        assertThat(firstRow.get(displayToActual.get("phone_no")).asText()).isEqualTo("9876543210");
    }
}
