package com.docflow.reports;

import com.docflow.reports.dto.DynamicReportRequest;
import com.docflow.reports.service.DynamicReportBuilder;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.Mockito;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.mock.mockito.SpyBean;
import org.springframework.http.MediaType;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.test.web.servlet.MockMvc;
import org.springframework.test.web.servlet.MvcResult;

import java.util.LinkedHashMap;
import java.util.Map;

import static org.assertj.core.api.Assertions.assertThat;
import static org.mockito.ArgumentMatchers.any;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.post;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.put;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.jsonPath;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;

@SpringBootTest(properties = {
        "spring.datasource.url=jdbc:h2:mem:reports_e2e;MODE=Oracle;DB_CLOSE_DELAY=-1",
        "spring.datasource.driverClassName=org.h2.Driver",
        "spring.datasource.username=sa",
        "spring.datasource.password=",
        "spring.liquibase.enabled=false",
        "spring.flyway.enabled=false",
        "spring.jpa.hibernate.ddl-auto=none"
})
@AutoConfigureMockMvc
class DynamicReportEndToEndTest {

    @Autowired
    MockMvc mockMvc;

    @Autowired
    JdbcTemplate jdbcTemplate;

    @Autowired
    ObjectMapper objectMapper;

    @SpyBean
    DynamicReportBuilder reportBuilder;

    @BeforeEach
    void setup() {
        jdbcTemplate.execute("CREATE TABLE IF NOT EXISTS DOCUMENT_PARENT (ID BIGINT PRIMARY KEY, DOCUMENT_NUMBER VARCHAR(50), STATUS VARCHAR(50), CREATED_AT TIMESTAMP)");
        jdbcTemplate.execute("CREATE TABLE IF NOT EXISTS LOAN_DATA (USER_ID VARCHAR(50), LOAN_AMOUNT NUMBER, COMPLETION_DATE DATE)");
        jdbcTemplate.execute("CREATE TABLE IF NOT EXISTS DOCUMENT_METADATA (DOCUMENT_ID BIGINT, FIELD_KEY VARCHAR(100), FIELD_VALUE CLOB)");
        jdbcTemplate.execute("CREATE TABLE IF NOT EXISTS report_templates (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name VARCHAR(255) NOT NULL, description VARCHAR(4000), config_json CLOB, created_by VARCHAR(100) DEFAULT 'SYSTEM' NOT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_by VARCHAR(100), updated_at TIMESTAMP)");
        jdbcTemplate.execute("CREATE TABLE IF NOT EXISTS DATE_PRESET_MASTER (ID BIGINT PRIMARY KEY, PRESET_CODE VARCHAR(100) NOT NULL, PRESET_NAME VARCHAR(200) NOT NULL, PRESET_DESCRIPTION VARCHAR(500), START_RULE VARCHAR(100) NOT NULL, END_RULE VARCHAR(100) NOT NULL, ENABLED CHAR(1) DEFAULT 'Y' NOT NULL, DISPLAY_ORDER INT DEFAULT 0 NOT NULL)");
        jdbcTemplate.execute("CREATE TABLE IF NOT EXISTS REPORT_FILTER_PRESET_MAP (ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, REPORT_CODE VARCHAR(150) NOT NULL, FILTER_KEY VARCHAR(200) NOT NULL, PRESET_CODE VARCHAR(100) NOT NULL, ENABLED CHAR(1) DEFAULT 'Y' NOT NULL, DISPLAY_ORDER INT DEFAULT 0 NOT NULL, CREATED_BY VARCHAR(100), CREATED_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP, UPDATED_BY VARCHAR(100), UPDATED_TIME TIMESTAMP)");

        jdbcTemplate.execute("DELETE FROM REPORT_FILTER_PRESET_MAP");
        jdbcTemplate.execute("DELETE FROM DATE_PRESET_MASTER");
        jdbcTemplate.execute("DELETE FROM DOCUMENT_METADATA");
        jdbcTemplate.execute("DELETE FROM LOAN_DATA");
        jdbcTemplate.execute("DELETE FROM DOCUMENT_PARENT");
        jdbcTemplate.execute("DELETE FROM report_templates");

        jdbcTemplate.update("INSERT INTO DATE_PRESET_MASTER (ID, PRESET_CODE, PRESET_NAME, PRESET_DESCRIPTION, START_RULE, END_RULE, ENABLED, DISPLAY_ORDER) VALUES (1, 'THIS_WEEK', 'This Week', 'Current week start to today', 'CURRENT_WEEK_START', 'TODAY', 'Y', 10)");
        jdbcTemplate.update("INSERT INTO DATE_PRESET_MASTER (ID, PRESET_CODE, PRESET_NAME, PRESET_DESCRIPTION, START_RULE, END_RULE, ENABLED, DISPLAY_ORDER) VALUES (2, 'PREVIOUS_WEEK', 'Previous Week', 'Previous week full range', 'PREVIOUS_WEEK_START', 'PREVIOUS_WEEK_END', 'Y', 20)");
        jdbcTemplate.update("INSERT INTO DATE_PRESET_MASTER (ID, PRESET_CODE, PRESET_NAME, PRESET_DESCRIPTION, START_RULE, END_RULE, ENABLED, DISPLAY_ORDER) VALUES (3, 'THIS_MONTH', 'This Month', 'Current month start to today', 'CURRENT_MONTH_START', 'TODAY', 'Y', 30)");
        jdbcTemplate.update("INSERT INTO DATE_PRESET_MASTER (ID, PRESET_CODE, PRESET_NAME, PRESET_DESCRIPTION, START_RULE, END_RULE, ENABLED, DISPLAY_ORDER) VALUES (4, 'PREVIOUS_MONTH', 'Previous Month', 'Previous month full range', 'PREVIOUS_MONTH_START', 'PREVIOUS_MONTH_END', 'Y', 40)");

        java.sql.Timestamp createdAt = java.sql.Timestamp.valueOf(java.time.LocalDateTime.now().withHour(10).withMinute(15).withSecond(30).withNano(0));
        jdbcTemplate.update("INSERT INTO DOCUMENT_PARENT (ID, DOCUMENT_NUMBER, STATUS, CREATED_AT) VALUES (?,?,?,?)", 1, "KYC001", "PENDING", createdAt);
        jdbcTemplate.update("INSERT INTO DOCUMENT_PARENT (ID, DOCUMENT_NUMBER, STATUS, CREATED_AT) VALUES (?,?,?,?)", 2, "KYC002", "DONE", java.sql.Timestamp.valueOf("2025-02-15 10:15:30"));
        jdbcTemplate.update("INSERT INTO LOAN_DATA (USER_ID, LOAN_AMOUNT, COMPLETION_DATE) VALUES (?,?,DATE '2025-12-31')", "KYC001", 2000000, null);
        jdbcTemplate.update("INSERT INTO DOCUMENT_METADATA (DOCUMENT_ID, FIELD_KEY, FIELD_VALUE) VALUES (?,?,?)", 1, "state", "\"Tamil Nadu\"");
        jdbcTemplate.update("INSERT INTO DOCUMENT_METADATA (DOCUMENT_ID, FIELD_KEY, FIELD_VALUE) VALUES (?,?,?)", 1, "age", "45");
    }

    @Test
    void endToEndReportFlow() throws Exception {
        Mockito.reset(reportBuilder);
        Mockito.doAnswer(invocation -> {
            DynamicReportBuilder.BuiltReport built = (DynamicReportBuilder.BuiltReport) invocation.callRealMethod();
            System.out.println("Generated SQL: " + built.sql());
            return built;
        }).when(reportBuilder).build(any(DynamicReportRequest.class));

        mockMvc.perform(get("/api/reports/admin/scope").param("baseEntity", "LOAN_DATA"))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.entities[0].name").value("DOCUMENT_PARENT"))
                .andExpect(jsonPath("$.baseColumns").isArray())
                .andExpect(jsonPath("$.metadataKeys").isArray());

        String templatePayload = """
                {
                  "name": "Loans over 15L",
                  "request": {
                    "baseEntity": "LOAN_DATA",
                    "columns": ["DOCUMENT_PARENT.DOCUMENT_NUMBER", "LOAN_AMOUNT", "COMPLETION_DATE", "meta:state"],
                    "filters": [
                      {"key": "LOAN_AMOUNT", "op": ">", "value": "1500000"},
                      {"key": "meta:state", "op": "=", "value": "Tamil Nadu"}
                    ]
                  }
                }
                """;

        MvcResult saveResult = mockMvc.perform(post("/api/reports/templates")
                        .contentType(MediaType.APPLICATION_JSON)
                        .header("X-USER-ID", "tester")
                        .content(templatePayload))
                .andExpect(status().isCreated())
                .andExpect(jsonPath("$.id").isNumber())
                .andExpect(jsonPath("$.name").value("Loans over 15L"))
                .andExpect(jsonPath("$.createdBy").value("tester"))
                .andReturn();

        long templateId = objectMapper.readTree(saveResult.getResponse().getContentAsString()).get("id").asLong();
        assertThat(templateId).isPositive();
        Map<String, Object> persistedTemplate = jdbcTemplate.queryForMap(
                "SELECT created_by, updated_by, updated_at FROM report_templates WHERE id = ?",
                templateId
        );
        assertThat(persistedTemplate.get("created_by")).isEqualTo("tester");
        assertThat(persistedTemplate.get("updated_by")).isNull();
        assertThat(persistedTemplate.get("updated_at")).isNull();

        mockMvc.perform(get("/api/reports/templates"))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.templates[0].id").value(templateId))
                .andExpect(jsonPath("$.templates[0].name").value("Loans over 15L"))
                .andExpect(jsonPath("$.templates[0].request.baseEntity").value("LOAN_DATA"));

        runCaseLoansOver15L();
        runCaseMetadataState();
        runCaseKycPending();
        runCaseMetadataAge();
        runCaseCompletionDateBetween();
        runCaseLoanAmountRange();
        runCaseLoanAmountAndMetadata();
        runCaseCreatedAt();
    }

    private void runCaseLoansOver15L() throws Exception {
        String payload = """
                {
                  "baseEntity": "LOAN_DATA",
                  "columns": ["DOCUMENT_PARENT.DOCUMENT_NUMBER", "LOAN_AMOUNT"],
                  "filters": [
                    {"key": "LOAN_AMOUNT", "op": ">", "value": "1500000"}
                  ]
                }
                """;

        MvcResult result = mockMvc.perform(post("/api/reports/run")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(payload))
                .andExpect(status().isOk())
                .andReturn();
        assertSingleDocument(result, "KYC001");
    }

    private void runCaseMetadataState() throws Exception {
        String payload = """
                {
                  "baseEntity": "LOAN_DATA",
                  "columns": ["DOCUMENT_PARENT.DOCUMENT_NUMBER", "meta:state"],
                  "filters": [
                    {"key": "meta:state", "op": "=", "value": "Tamil Nadu"}
                  ]
                }
                """;
        MvcResult result = mockMvc.perform(post("/api/reports/run")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(payload))
                .andExpect(status().isOk())
                .andReturn();
        JsonNode json = objectMapper.readTree(result.getResponse().getContentAsString());
        String state = json.get("rows").get(0).get("meta:state").asText();
        assertThat(state.replace("\"", "")).isEqualTo("Tamil Nadu");
        assertSingleDocument(result, "KYC001");
    }

    private void runCaseKycPending() throws Exception {
        String payload = """
                {
                  "baseEntity": "DOCUMENT_PARENT",
                  "columns": ["DOCUMENT_NUMBER", "STATUS"],
                  "filters": [
                    {"key": "STATUS", "op": "=", "value": "PENDING"}
                  ]
                }
                """;
        MvcResult result = mockMvc.perform(post("/api/reports/run")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(payload))
                .andExpect(status().isOk())
                .andReturn();
        assertSingleDocument(result, "KYC001");
    }

    private void runCaseMetadataAge() throws Exception {
        String payload = """
                {
                  "baseEntity": "DOCUMENT_PARENT",
                  "columns": ["DOCUMENT_NUMBER"],
                  "filters": [
                    {"key": "meta:age", "op": "<", "value": "50", "dataType": "number"}
                  ]
                }
                """;
        MvcResult result = mockMvc.perform(post("/api/reports/run")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(payload))
                .andExpect(status().isOk())
                .andReturn();
        assertSingleDocument(result, "KYC001");
    }

    private void runCaseCompletionDateBetween() throws Exception {
        String payload = """
                {
                  "baseEntity": "LOAN_DATA",
                  "columns": ["DOCUMENT_PARENT.DOCUMENT_NUMBER", "COMPLETION_DATE"],
                  "filters": [
                    {"key": "COMPLETION_DATE", "op": "BETWEEN", "valueFrom": "2025-01-01", "valueTo": "2025-12-31", "dataType": "date"}
                  ]
                }
                """;
        MvcResult result = mockMvc.perform(post("/api/reports/run")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(payload))
                .andExpect(status().isOk())
                .andReturn();
        assertSingleDocument(result, "KYC001");
    }

    private void runCaseLoanAmountRange() throws Exception {
        String payload = """
                {
                  "baseEntity": "LOAN_DATA",
                  "columns": ["DOCUMENT_PARENT.DOCUMENT_NUMBER", "LOAN_AMOUNT"],
                  "filters": [
                    {"key": "LOAN_AMOUNT", "op": "RANGE", "valueFrom": "1500000", "valueTo": "2500000", "dataType": "number"}
                  ]
                }
                """;
        MvcResult result = mockMvc.perform(post("/api/reports/run")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(payload))
                .andExpect(status().isOk())
                .andReturn();
        assertSingleDocument(result, "KYC001");
    }

    private void runCaseLoanAmountAndMetadata() throws Exception {
        String payload = """
                {
                  "baseEntity": "LOAN_DATA",
                  "columns": ["DOCUMENT_PARENT.DOCUMENT_NUMBER", "LOAN_AMOUNT", "meta:state"],
                  "filters": [
                    {"key": "LOAN_AMOUNT", "op": ">", "value": "1500000"},
                    {"key": "meta:state", "op": "=", "value": "Tamil Nadu"}
                  ]
                }
                """;
        MvcResult result = mockMvc.perform(post("/api/reports/run")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(payload))
                .andExpect(status().isOk())
                .andReturn();
        assertSingleDocument(result, "KYC001");
    }

    private void runCaseCreatedAt() throws Exception {
        String payload = """
                {
                  "baseEntity": "DOCUMENT_PARENT",
                  "columns": ["DOCUMENT_NUMBER", "CREATED_AT"],
                  "filters": [
                    {"key": "STATUS", "op": "=", "value": "PENDING"}
                  ]
                }
                """;
        MvcResult result = mockMvc.perform(post("/api/reports/run")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(payload))
                .andExpect(status().isOk())
                .andReturn();
        JsonNode json = objectMapper.readTree(result.getResponse().getContentAsString());
        JsonNode createdAt = json.get("rows").get(0).get("CREATED_AT");
        assertThat(createdAt.isTextual()).isTrue();
        assertThat(createdAt.asText()).contains("T");
    }

    @Test
    void metadataFilterHonorsPagination() throws Exception {
        java.sql.Timestamp createdAt = java.sql.Timestamp.valueOf("2025-02-15 10:15:30");
        jdbcTemplate.update("INSERT INTO DOCUMENT_PARENT (ID, DOCUMENT_NUMBER, STATUS, CREATED_AT) VALUES (?,?,?,?)", 3, "KYC003", "PENDING", createdAt);
        jdbcTemplate.update("INSERT INTO DOCUMENT_METADATA (DOCUMENT_ID, FIELD_KEY, FIELD_VALUE) VALUES (?,?,?)", 3, "state", "\"Tamil Nadu\"");

        String payload = """
                {
                  "baseEntity": "DOCUMENT_PARENT",
                  "columns": ["DOCUMENT_NUMBER"],
                  "filters": [
                    {"key": "meta:state", "op": "=", "value": "Tamil Nadu"}
                  ]
                }
                """;
        MvcResult firstPage = mockMvc.perform(post("/api/reports/run")
                        .contentType(MediaType.APPLICATION_JSON)
                        .param("page", "0")
                        .param("size", "1")
                        .content(payload))
                .andExpect(status().isOk())
                .andReturn();
        MvcResult secondPage = mockMvc.perform(post("/api/reports/run")
                        .contentType(MediaType.APPLICATION_JSON)
                        .param("page", "1")
                        .param("size", "1")
                        .content(payload))
                .andExpect(status().isOk())
                .andReturn();

        JsonNode firstJson = objectMapper.readTree(firstPage.getResponse().getContentAsString());
        JsonNode secondJson = objectMapper.readTree(secondPage.getResponse().getContentAsString());
        assertThat(firstJson.get("rows").size()).isEqualTo(1);
        assertThat(secondJson.get("rows").size()).isEqualTo(1);
    }

    @Test
    void updatingTemplatePreservesCreatedAuditAndPopulatesUpdatedAudit() throws Exception {
        String createPayload = """
                {
                  "name": "Original Template",
                  "request": {
                    "baseEntity": "DOCUMENT_PARENT",
                    "columns": ["DOCUMENT_NUMBER"],
                    "filters": [
                      {"key": "STATUS", "op": "=", "value": "PENDING"}
                    ]
                  }
                }
                """;

        MvcResult createResult = mockMvc.perform(post("/api/reports/templates")
                        .contentType(MediaType.APPLICATION_JSON)
                        .header("X-USER-ID", "creator1")
                        .content(createPayload))
                .andExpect(status().isCreated())
                .andReturn();

        long templateId = objectMapper.readTree(createResult.getResponse().getContentAsString()).get("id").asLong();
        Map<String, Object> beforeUpdate = jdbcTemplate.queryForMap(
                "SELECT created_by, created_at, updated_by, updated_at FROM report_templates WHERE id = ?",
                templateId
        );

        String updatePayload = """
                {
                  "name": "Updated Template",
                  "request": {
                    "baseEntity": "DOCUMENT_PARENT",
                    "columns": ["DOCUMENT_NUMBER", "STATUS"],
                    "filters": [
                      {"key": "STATUS", "op": "=", "value": "DONE"}
                    ]
                  }
                }
                """;

        mockMvc.perform(put("/api/reports/templates/{id}", templateId)
                        .contentType(MediaType.APPLICATION_JSON)
                        .header("X-USER-ID", "editor1")
                        .content(updatePayload))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.name").value("Updated Template"))
                .andExpect(jsonPath("$.createdBy").value("creator1"));

        Map<String, Object> afterUpdate = jdbcTemplate.queryForMap(
                "SELECT created_by, created_at, updated_by, updated_at FROM report_templates WHERE id = ?",
                templateId
        );

        assertThat(afterUpdate.get("created_by")).isEqualTo(beforeUpdate.get("created_by"));
        assertThat(afterUpdate.get("created_at")).isEqualTo(beforeUpdate.get("created_at"));
        assertThat(afterUpdate.get("updated_by")).isEqualTo("editor1");
        assertThat(afterUpdate.get("updated_at")).isNotNull();
    }

    @Test
    void adminTemplateSaveReadAndExecutionSupportPresetMappings() throws Exception {
        mockMvc.perform(get("/api/reports/admin/scope"))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.presets[0].code").value("THIS_WEEK"));

        String createPayload = """
                {
                  "name": "Date Preset Template",
                  "request": {
                    "baseEntity": "LOAN_DATA",
                    "columns": ["DOCUMENT_PARENT.DOCUMENT_NUMBER", "COMPLETION_DATE"],
                    "filters": [
                      {
                        "key": "DOCUMENT_PARENT.CREATED_AT",
                        "op": "BETWEEN",
                        "mode": "USER_INPUT",
                        "logicalType": "DATE",
                        "dataType": "DATE",
                        "presetCodes": ["THIS_WEEK", "THIS_MONTH"]
                      },
                      {
                        "key": "COMPLETION_DATE",
                        "op": "BETWEEN",
                        "mode": "USER_INPUT",
                        "logicalType": "DATE",
                        "dataType": "DATE",
                        "presetCodes": ["THIS_MONTH"]
                      }
                    ]
                  }
                }
                """;

        MvcResult createResult = mockMvc.perform(post("/api/reports/templates")
                        .contentType(MediaType.APPLICATION_JSON)
                        .header("X-USER-ID", "admin1")
                        .content(createPayload))
                .andExpect(status().isCreated())
                .andExpect(jsonPath("$.request.filters[0].presetCodes[0]").value("THIS_WEEK"))
                .andReturn();

        long templateId = objectMapper.readTree(createResult.getResponse().getContentAsString()).get("id").asLong();
        assertThat(jdbcTemplate.queryForObject(
                "SELECT COUNT(*) FROM REPORT_FILTER_PRESET_MAP WHERE REPORT_CODE = ?",
                Integer.class,
                "Date Preset Template"
        )).isEqualTo(3);

        mockMvc.perform(get("/api/reports/templates"))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.templates[0].request.filters[0].presetCodes[0]").value("THIS_WEEK"));

        mockMvc.perform(get("/api/reports/templates/{id}", templateId))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.filters[0].presetEnabled").value(true))
                .andExpect(jsonPath("$.filters[0].presets[0].code").value("THIS_WEEK"));

        String runPayload = """
                {
                  "templateId": %d,
                  "filters": [
                    {
                      "key": "DOCUMENT_PARENT.CREATED_AT",
                      "mode": "PRESET",
                      "presetCode": "THIS_MONTH"
                    },
                    {
                      "key": "COMPLETION_DATE",
                      "mode": "MANUAL",
                      "op": "BETWEEN",
                      "valueFrom": "2025-01-01",
                      "valueTo": "2025-12-31"
                    }
                  ]
                }
                """.formatted(templateId);

        MvcResult runResult = mockMvc.perform(post("/api/reports/run")
                        .param("mode", "exec")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(runPayload))
                .andExpect(status().isOk())
                .andReturn();

        JsonNode json = objectMapper.readTree(runResult.getResponse().getContentAsString());
        assertThat(json.get("rows").size()).isEqualTo(1);
        assertThat(json.get("rows").get(0).toString()).contains("KYC001");
    }

    @Test
    void updateTemplateRefreshesPresetMappingsAndRemovesStaleRows() throws Exception {
        String createPayload = """
                {
                  "name": "Preset Rename Source",
                  "request": {
                    "baseEntity": "DOCUMENT_PARENT",
                    "columns": ["DOCUMENT_NUMBER"],
                    "filters": [
                      {
                        "key": "CREATED_AT",
                        "op": "BETWEEN",
                        "mode": "USER_INPUT",
                        "logicalType": "DATE",
                        "dataType": "DATE",
                        "presetCodes": ["THIS_WEEK", "THIS_MONTH"]
                      }
                    ]
                  }
                }
                """;

        long templateId = objectMapper.readTree(mockMvc.perform(post("/api/reports/templates")
                        .contentType(MediaType.APPLICATION_JSON)
                        .header("X-USER-ID", "creator1")
                        .content(createPayload))
                .andExpect(status().isCreated())
                .andReturn().getResponse().getContentAsString()).get("id").asLong();

        String updatePayload = """
                {
                  "name": "Preset Rename Target",
                  "request": {
                    "baseEntity": "DOCUMENT_PARENT",
                    "columns": ["DOCUMENT_NUMBER"],
                    "filters": [
                      {
                        "key": "CREATED_AT",
                        "op": "BETWEEN",
                        "mode": "USER_INPUT",
                        "logicalType": "DATE",
                        "dataType": "DATE",
                        "presetCodes": ["PREVIOUS_WEEK"]
                      }
                    ]
                  }
                }
                """;

        mockMvc.perform(put("/api/reports/templates/{id}", templateId)
                        .contentType(MediaType.APPLICATION_JSON)
                        .header("X-USER-ID", "editor1")
                        .content(updatePayload))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.name").value("Preset Rename Target"))
                .andExpect(jsonPath("$.request.filters[0].presetCodes[0]").value("PREVIOUS_WEEK"));

        assertThat(jdbcTemplate.queryForObject(
                "SELECT COUNT(*) FROM REPORT_FILTER_PRESET_MAP WHERE REPORT_CODE = ?",
                Integer.class,
                "Preset Rename Source"
        )).isEqualTo(0);
        assertThat(jdbcTemplate.queryForObject(
                "SELECT COUNT(*) FROM REPORT_FILTER_PRESET_MAP WHERE REPORT_CODE = ? AND PRESET_CODE = ?",
                Integer.class,
                "Preset Rename Target",
                "PREVIOUS_WEEK"
        )).isEqualTo(1);
    }

    @Test
    void rejectsPresetMappingsForNonDateFilters() throws Exception {
        String payload = """
                {
                  "name": "Invalid Preset Template",
                  "request": {
                    "baseEntity": "DOCUMENT_PARENT",
                    "columns": ["DOCUMENT_NUMBER"],
                    "filters": [
                      {
                        "key": "STATUS",
                        "op": "=",
                        "mode": "USER_INPUT",
                        "logicalType": "STRING",
                        "dataType": "STRING",
                        "presetCodes": ["THIS_WEEK"]
                      }
                    ]
                  }
                }
                """;

        mockMvc.perform(post("/api/reports/templates")
                        .contentType(MediaType.APPLICATION_JSON)
                        .header("X-USER-ID", "admin1")
                        .content(payload))
                .andExpect(status().isBadRequest())
                .andExpect(jsonPath("$.message").value(org.hamcrest.Matchers.containsString("DATE filters")));
    }

    private void assertSingleDocument(MvcResult result, String expectedDocumentNumber) throws Exception {
        JsonNode json = objectMapper.readTree(result.getResponse().getContentAsString());
        assertThat(json.get("rows").isArray()).isTrue();
        assertThat(json.get("rows").size()).isEqualTo(1);
        Map<String, String> displayToActual = new LinkedHashMap<>();
        for (JsonNode columnNode : json.get("columns")) {
            String actualName = columnNode.asText();
            String displayName = actualName.contains(".") ? actualName.substring(actualName.indexOf('.') + 1) : actualName;
            displayToActual.put(displayName, actualName);
        }
        assertThat(json.get("rows").get(0).get(displayToActual.get("DOCUMENT_NUMBER")).asText()).isEqualTo(expectedDocumentNumber);
    }
}
