export type ModuleCode =
  | 'UPLOAD'
  | 'REVIEW'
  | 'FAST_TRACK_APPROVAL'
  | 'APPROVAL'
  | 'REPORTS'
  | 'REPORT_CONFIG'
  | 'AUDIT'
  | 'DATA_INGEST'
  | 'ADMIN';

export const ModuleCodes: Record<ModuleCode, ModuleCode> = {
  UPLOAD: 'UPLOAD',
  REVIEW: 'REVIEW',
  FAST_TRACK_APPROVAL: 'FAST_TRACK_APPROVAL',
  APPROVAL: 'APPROVAL',
  REPORTS: 'REPORTS',
  REPORT_CONFIG: 'REPORT_CONFIG',
  AUDIT: 'AUDIT',
  DATA_INGEST: 'DATA_INGEST',
  ADMIN: 'ADMIN',
};
