DECLARE
    v_count INTEGER;
BEGIN
    SELECT COUNT(*) INTO v_count
    FROM ALL_CONSTRAINTS
    WHERE CONSTRAINT_NAME = 'REPORT_TEMPLATES_NAME_UK'
      AND TABLE_NAME = 'REPORT_TEMPLATES';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE '
            ALTER TABLE REPORT_TEMPLATES
            ADD CONSTRAINT REPORT_TEMPLATES_NAME_UK UNIQUE (NAME)';
    END IF;
END;
/
