DECLARE
    v_count INTEGER;
BEGIN
    SELECT COUNT(*) INTO v_count
    FROM USER_TAB_COLUMNS
    WHERE TABLE_NAME = 'REPORT_TEMPLATES'
      AND COLUMN_NAME = 'CREATED_BY';

    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE REPORT_TEMPLATES ADD (CREATED_BY VARCHAR2(100) DEFAULT ''SYSTEM'' NOT NULL)';
    END IF;

    SELECT COUNT(*) INTO v_count
    FROM USER_TAB_COLUMNS
    WHERE TABLE_NAME = 'REPORT_TEMPLATES'
      AND COLUMN_NAME = 'UPDATED_AT';

    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE REPORT_TEMPLATES ADD (UPDATED_AT TIMESTAMP)';
    END IF;

    SELECT COUNT(*) INTO v_count
    FROM USER_TAB_COLUMNS
    WHERE TABLE_NAME = 'REPORT_TEMPLATES'
      AND COLUMN_NAME = 'UPDATED_BY';

    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE REPORT_TEMPLATES ADD (UPDATED_BY VARCHAR2(100))';
    END IF;

    EXECUTE IMMEDIATE 'ALTER TABLE REPORT_TEMPLATES MODIFY (CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL)';
    EXECUTE IMMEDIATE 'ALTER TABLE REPORT_TEMPLATES MODIFY (CREATED_BY VARCHAR2(100) DEFAULT ''SYSTEM'' NOT NULL)';
END;
/
