version: '3.8'

services:
  backend:
    build:
      context: ../backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:oracle:thin:@host.docker.internal:1522/XEPDB1
      SPRING_DATASOURCE_USERNAME: DOCFLOW_EXP
      SPRING_DATASOURCE_PASSWORD: docflow_exp
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ../frontend
    depends_on:
      - backend
    ports:
      - "3000:80"