version: '3.8'
services:
  oracle:
    image: gvenzl/oracle-xe:21-slim
    container_name: docflow-oracle
    ports:
      - "1522:1521"
    environment:
      ORACLE_PASSWORD: docflow
      APP_USER: docflow
      APP_USER_PASSWORD: docflow
    healthcheck:
      test: ["CMD", "healthcheck.sh"]
      interval: 30s
      timeout: 10s
      retries: 10
  backend:
    build:
      context: ../backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:oracle:thin:@oracle:1521/FREEPDB1
      SPRING_DATASOURCE_USERNAME: docflow
      SPRING_DATASOURCE_PASSWORD: docflow
    depends_on:
      oracle:
        condition: service_healthy
    ports:
      - "8080:8080"
  frontend:
    build:
      context: ../frontend
    depends_on:
      - backend
    ports:
      - "3000:80"
