-- Client-1 bootstrap seed script (idempotent).
-- Safe to re-run; uses MERGE statements and guarded CREATE TABLE blocks.

/* ============================================================================
   A) Optional table creation (guarded by ALL_TABLES checks)
   ============================================================================ */
DECLARE
  v_count INTEGER;
BEGIN
  SELECT COUNT(*) INTO v_count FROM ALL_TABLES WHERE TABLE_NAME = 'ROLES';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE '
      CREATE TABLE ROLES (
        ROLE_NAME  VARCHAR2(50) PRIMARY KEY,
        DESCRIPTION VARCHAR2(255),
        ENABLED    CHAR(1) DEFAULT ''Y'' NOT NULL,
        CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
      )';
  END IF;
END;
/

DECLARE
  v_count INTEGER;
BEGIN
  SELECT COUNT(*) INTO v_count FROM ALL_TABLES WHERE TABLE_NAME = 'USER_ROLE_MAP';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE '
      CREATE TABLE USER_ROLE_MAP (
        USER_ID    VARCHAR2(200) NOT NULL,
        ROLE_NAME  VARCHAR2(50)  NOT NULL,
        ENABLED    CHAR(1)       DEFAULT ''Y'' NOT NULL,
        CREATED_AT TIMESTAMP     DEFAULT CURRENT_TIMESTAMP,
        UPDATED_AT TIMESTAMP,
        CONSTRAINT PK_USER_ROLE_MAP PRIMARY KEY (USER_ID, ROLE_NAME),
        CONSTRAINT FK_USER_ROLE_MAP_ROLE_NAME FOREIGN KEY (ROLE_NAME) REFERENCES ROLES(ROLE_NAME)
      )';
  END IF;
END;
/

DECLARE
  v_count INTEGER;
BEGIN
  SELECT COUNT(*) INTO v_count FROM ALL_TABLES WHERE TABLE_NAME = 'ROLE_MODULE_ACCESS';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE '
      CREATE TABLE ROLE_MODULE_ACCESS (
        ROLE        VARCHAR2(50)  NOT NULL,
        MODULE_CODE VARCHAR2(100) NOT NULL,
        ENABLED     CHAR(1)       DEFAULT ''Y'' NOT NULL,
        CREATED_AT  TIMESTAMP     DEFAULT CURRENT_TIMESTAMP,
        UPDATED_AT  TIMESTAMP,
        CONSTRAINT PK_ROLE_MODULE_ACCESS PRIMARY KEY (ROLE, MODULE_CODE),
        CONSTRAINT FK_ROLE_MODULE_ACCESS_ROLE FOREIGN KEY (ROLE) REFERENCES ROLES(ROLE_NAME)
      )';
  END IF;
END;
/

DECLARE
  v_count INTEGER;
BEGIN
  SELECT COUNT(*) INTO v_count FROM ALL_TABLES WHERE TABLE_NAME = 'WORKFLOW_ACTIONS';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE '
      CREATE TABLE WORKFLOW_ACTIONS (
        ACTION_CODE VARCHAR2(50) PRIMARY KEY,
        LABEL       VARCHAR2(100) NOT NULL,
        ENABLED     CHAR(1) DEFAULT ''Y'' NOT NULL,
        CREATED_AT  TIMESTAMP DEFAULT CURRENT_TIMESTAMP
      )';
  END IF;
END;
/

DECLARE
  v_count INTEGER;
BEGIN
  SELECT COUNT(*) INTO v_count FROM ALL_TABLES WHERE TABLE_NAME = 'ROLE_WORKFLOW_ACTION_ACCESS';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE '
      CREATE TABLE ROLE_WORKFLOW_ACTION_ACCESS (
        ROLE_NAME   VARCHAR2(50) NOT NULL,
        FROM_STATUS VARCHAR2(50) NOT NULL,
        ACTION_CODE VARCHAR2(50) NOT NULL,
        ENABLED     CHAR(1) DEFAULT ''Y'' NOT NULL,
        CREATED_AT  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        UPDATED_AT  TIMESTAMP,
        CONSTRAINT PK_ROLE_WORKFLOW_ACTION_ACCESS PRIMARY KEY (ROLE_NAME, FROM_STATUS, ACTION_CODE),
        CONSTRAINT FK_ROLE_WORKFLOW_ACTION_ROLE FOREIGN KEY (ROLE_NAME) REFERENCES ROLES(ROLE_NAME),
        CONSTRAINT FK_ROLE_WORKFLOW_ACTION_CODE FOREIGN KEY (ACTION_CODE) REFERENCES WORKFLOW_ACTIONS(ACTION_CODE)
      )';
    EXECUTE IMMEDIATE 'CREATE INDEX IDX_RWF_ACTION_STATUS ON ROLE_WORKFLOW_ACTION_ACCESS (FROM_STATUS)';
    EXECUTE IMMEDIATE 'CREATE INDEX IDX_RWF_ACTION_ROLE ON ROLE_WORKFLOW_ACTION_ACCESS (ROLE_NAME)';
  END IF;
END;
/

/* ============================================================================
   B) Seed ROLES (Client-1 roles)
   ============================================================================ */
MERGE INTO ROLES t
USING (SELECT 'MAKER' AS ROLE_NAME, 'Maker' AS DESCRIPTION FROM dual) s
ON (t.ROLE_NAME = s.ROLE_NAME)
WHEN NOT MATCHED THEN
  INSERT (ROLE_NAME, DESCRIPTION, ENABLED) VALUES (s.ROLE_NAME, s.DESCRIPTION, 'Y');

MERGE INTO ROLES t
USING (SELECT 'REVIEWER' AS ROLE_NAME, 'Reviewer' AS DESCRIPTION FROM dual) s
ON (t.ROLE_NAME = s.ROLE_NAME)
WHEN NOT MATCHED THEN
  INSERT (ROLE_NAME, DESCRIPTION, ENABLED) VALUES (s.ROLE_NAME, s.DESCRIPTION, 'Y');

MERGE INTO ROLES t
USING (SELECT 'FACILITATOR' AS ROLE_NAME, 'Facilitator' AS DESCRIPTION FROM dual) s
ON (t.ROLE_NAME = s.ROLE_NAME)
WHEN NOT MATCHED THEN
  INSERT (ROLE_NAME, DESCRIPTION, ENABLED) VALUES (s.ROLE_NAME, s.DESCRIPTION, 'Y');

MERGE INTO ROLES t
USING (SELECT 'APPROVER' AS ROLE_NAME, 'Approver' AS DESCRIPTION FROM dual) s
ON (t.ROLE_NAME = s.ROLE_NAME)
WHEN NOT MATCHED THEN
  INSERT (ROLE_NAME, DESCRIPTION, ENABLED) VALUES (s.ROLE_NAME, s.DESCRIPTION, 'Y');

/* ============================================================================
   C) Seed WORKFLOW_ACTIONS
   ============================================================================ */
MERGE INTO WORKFLOW_ACTIONS t
USING (SELECT 'SUBMIT' AS ACTION_CODE, 'Submit for Review' AS LABEL FROM dual) s
ON (t.ACTION_CODE = s.ACTION_CODE)
WHEN NOT MATCHED THEN
  INSERT (ACTION_CODE, LABEL, ENABLED) VALUES (s.ACTION_CODE, s.LABEL, 'Y');

MERGE INTO WORKFLOW_ACTIONS t
USING (SELECT 'START_REVIEW' AS ACTION_CODE, 'Start Review' AS LABEL FROM dual) s
ON (t.ACTION_CODE = s.ACTION_CODE)
WHEN NOT MATCHED THEN
  INSERT (ACTION_CODE, LABEL, ENABLED) VALUES (s.ACTION_CODE, s.LABEL, 'Y');

MERGE INTO WORKFLOW_ACTIONS t
USING (SELECT 'APPROVE' AS ACTION_CODE, 'Approve' AS LABEL FROM dual) s
ON (t.ACTION_CODE = s.ACTION_CODE)
WHEN NOT MATCHED THEN
  INSERT (ACTION_CODE, LABEL, ENABLED) VALUES (s.ACTION_CODE, s.LABEL, 'Y');

MERGE INTO WORKFLOW_ACTIONS t
USING (SELECT 'REJECT' AS ACTION_CODE, 'Reject' AS LABEL FROM dual) s
ON (t.ACTION_CODE = s.ACTION_CODE)
WHEN NOT MATCHED THEN
  INSERT (ACTION_CODE, LABEL, ENABLED) VALUES (s.ACTION_CODE, s.LABEL, 'Y');

MERGE INTO WORKFLOW_ACTIONS t
USING (SELECT 'REWORK' AS ACTION_CODE, 'Rework' AS LABEL FROM dual) s
ON (t.ACTION_CODE = s.ACTION_CODE)
WHEN NOT MATCHED THEN
  INSERT (ACTION_CODE, LABEL, ENABLED) VALUES (s.ACTION_CODE, s.LABEL, 'Y');

MERGE INTO WORKFLOW_ACTIONS t
USING (SELECT 'CLOSE' AS ACTION_CODE, 'Close Document' AS LABEL FROM dual) s
ON (t.ACTION_CODE = s.ACTION_CODE)
WHEN NOT MATCHED THEN
  INSERT (ACTION_CODE, LABEL, ENABLED) VALUES (s.ACTION_CODE, s.LABEL, 'Y');

/* ============================================================================
   D) Seed ROLE_WORKFLOW_ACTION_ACCESS (DocumentStatus: DRAFT, OPEN, UNDER_REVIEW, REWORK, APPROVED, REJECTED, CLOSED)
   ============================================================================ */
MERGE INTO ROLE_WORKFLOW_ACTION_ACCESS t
USING (SELECT 'MAKER' AS ROLE_NAME, 'DRAFT' AS FROM_STATUS, 'SUBMIT' AS ACTION_CODE FROM dual) s
ON (t.ROLE_NAME = s.ROLE_NAME AND t.FROM_STATUS = s.FROM_STATUS AND t.ACTION_CODE = s.ACTION_CODE)
WHEN NOT MATCHED THEN
  INSERT (ROLE_NAME, FROM_STATUS, ACTION_CODE, ENABLED) VALUES (s.ROLE_NAME, s.FROM_STATUS, s.ACTION_CODE, 'Y');

MERGE INTO ROLE_WORKFLOW_ACTION_ACCESS t
USING (SELECT 'MAKER' AS ROLE_NAME, 'REWORK' AS FROM_STATUS, 'SUBMIT' AS ACTION_CODE FROM dual) s
ON (t.ROLE_NAME = s.ROLE_NAME AND t.FROM_STATUS = s.FROM_STATUS AND t.ACTION_CODE = s.ACTION_CODE)
WHEN NOT MATCHED THEN
  INSERT (ROLE_NAME, FROM_STATUS, ACTION_CODE, ENABLED) VALUES (s.ROLE_NAME, s.FROM_STATUS, s.ACTION_CODE, 'Y');

MERGE INTO ROLE_WORKFLOW_ACTION_ACCESS t
USING (SELECT 'REVIEWER' AS ROLE_NAME, 'OPEN' AS FROM_STATUS, 'START_REVIEW' AS ACTION_CODE FROM dual) s
ON (t.ROLE_NAME = s.ROLE_NAME AND t.FROM_STATUS = s.FROM_STATUS AND t.ACTION_CODE = s.ACTION_CODE)
WHEN NOT MATCHED THEN
  INSERT (ROLE_NAME, FROM_STATUS, ACTION_CODE, ENABLED) VALUES (s.ROLE_NAME, s.FROM_STATUS, s.ACTION_CODE, 'Y');

MERGE INTO ROLE_WORKFLOW_ACTION_ACCESS t
USING (SELECT 'REVIEWER' AS ROLE_NAME, 'UNDER_REVIEW' AS FROM_STATUS, 'APPROVE' AS ACTION_CODE FROM dual) s
ON (t.ROLE_NAME = s.ROLE_NAME AND t.FROM_STATUS = s.FROM_STATUS AND t.ACTION_CODE = s.ACTION_CODE)
WHEN NOT MATCHED THEN
  INSERT (ROLE_NAME, FROM_STATUS, ACTION_CODE, ENABLED) VALUES (s.ROLE_NAME, s.FROM_STATUS, s.ACTION_CODE, 'Y');

MERGE INTO ROLE_WORKFLOW_ACTION_ACCESS t
USING (SELECT 'REVIEWER' AS ROLE_NAME, 'UNDER_REVIEW' AS FROM_STATUS, 'REJECT' AS ACTION_CODE FROM dual) s
ON (t.ROLE_NAME = s.ROLE_NAME AND t.FROM_STATUS = s.FROM_STATUS AND t.ACTION_CODE = s.ACTION_CODE)
WHEN NOT MATCHED THEN
  INSERT (ROLE_NAME, FROM_STATUS, ACTION_CODE, ENABLED) VALUES (s.ROLE_NAME, s.FROM_STATUS, s.ACTION_CODE, 'Y');

MERGE INTO ROLE_WORKFLOW_ACTION_ACCESS t
USING (SELECT 'REVIEWER' AS ROLE_NAME, 'UNDER_REVIEW' AS FROM_STATUS, 'REWORK' AS ACTION_CODE FROM dual) s
ON (t.ROLE_NAME = s.ROLE_NAME AND t.FROM_STATUS = s.FROM_STATUS AND t.ACTION_CODE = s.ACTION_CODE)
WHEN NOT MATCHED THEN
  INSERT (ROLE_NAME, FROM_STATUS, ACTION_CODE, ENABLED) VALUES (s.ROLE_NAME, s.FROM_STATUS, s.ACTION_CODE, 'Y');

MERGE INTO ROLE_WORKFLOW_ACTION_ACCESS t
USING (SELECT 'APPROVER' AS ROLE_NAME, 'UNDER_REVIEW' AS FROM_STATUS, 'APPROVE' AS ACTION_CODE FROM dual) s
ON (t.ROLE_NAME = s.ROLE_NAME AND t.FROM_STATUS = s.FROM_STATUS AND t.ACTION_CODE = s.ACTION_CODE)
WHEN NOT MATCHED THEN
  INSERT (ROLE_NAME, FROM_STATUS, ACTION_CODE, ENABLED) VALUES (s.ROLE_NAME, s.FROM_STATUS, s.ACTION_CODE, 'Y');

MERGE INTO ROLE_WORKFLOW_ACTION_ACCESS t
USING (SELECT 'APPROVER' AS ROLE_NAME, 'UNDER_REVIEW' AS FROM_STATUS, 'REJECT' AS ACTION_CODE FROM dual) s
ON (t.ROLE_NAME = s.ROLE_NAME AND t.FROM_STATUS = s.FROM_STATUS AND t.ACTION_CODE = s.ACTION_CODE)
WHEN NOT MATCHED THEN
  INSERT (ROLE_NAME, FROM_STATUS, ACTION_CODE, ENABLED) VALUES (s.ROLE_NAME, s.FROM_STATUS, s.ACTION_CODE, 'Y');

MERGE INTO ROLE_WORKFLOW_ACTION_ACCESS t
USING (SELECT 'APPROVER' AS ROLE_NAME, 'UNDER_REVIEW' AS FROM_STATUS, 'REWORK' AS ACTION_CODE FROM dual) s
ON (t.ROLE_NAME = s.ROLE_NAME AND t.FROM_STATUS = s.FROM_STATUS AND t.ACTION_CODE = s.ACTION_CODE)
WHEN NOT MATCHED THEN
  INSERT (ROLE_NAME, FROM_STATUS, ACTION_CODE, ENABLED) VALUES (s.ROLE_NAME, s.FROM_STATUS, s.ACTION_CODE, 'Y');

MERGE INTO ROLE_WORKFLOW_ACTION_ACCESS t
USING (SELECT 'FACILITATOR' AS ROLE_NAME, 'DRAFT' AS FROM_STATUS, 'SUBMIT' AS ACTION_CODE FROM dual) s
ON (t.ROLE_NAME = s.ROLE_NAME AND t.FROM_STATUS = s.FROM_STATUS AND t.ACTION_CODE = s.ACTION_CODE)
WHEN NOT MATCHED THEN
  INSERT (ROLE_NAME, FROM_STATUS, ACTION_CODE, ENABLED) VALUES (s.ROLE_NAME, s.FROM_STATUS, s.ACTION_CODE, 'Y');

MERGE INTO ROLE_WORKFLOW_ACTION_ACCESS t
USING (SELECT 'FACILITATOR' AS ROLE_NAME, 'REWORK' AS FROM_STATUS, 'SUBMIT' AS ACTION_CODE FROM dual) s
ON (t.ROLE_NAME = s.ROLE_NAME AND t.FROM_STATUS = s.FROM_STATUS AND t.ACTION_CODE = s.ACTION_CODE)
WHEN NOT MATCHED THEN
  INSERT (ROLE_NAME, FROM_STATUS, ACTION_CODE, ENABLED) VALUES (s.ROLE_NAME, s.FROM_STATUS, s.ACTION_CODE, 'Y');

MERGE INTO ROLE_WORKFLOW_ACTION_ACCESS t
USING (SELECT 'FACILITATOR' AS ROLE_NAME, 'OPEN' AS FROM_STATUS, 'START_REVIEW' AS ACTION_CODE FROM dual) s
ON (t.ROLE_NAME = s.ROLE_NAME AND t.FROM_STATUS = s.FROM_STATUS AND t.ACTION_CODE = s.ACTION_CODE)
WHEN NOT MATCHED THEN
  INSERT (ROLE_NAME, FROM_STATUS, ACTION_CODE, ENABLED) VALUES (s.ROLE_NAME, s.FROM_STATUS, s.ACTION_CODE, 'Y');

MERGE INTO ROLE_WORKFLOW_ACTION_ACCESS t
USING (SELECT 'FACILITATOR' AS ROLE_NAME, 'UNDER_REVIEW' AS FROM_STATUS, 'APPROVE' AS ACTION_CODE FROM dual) s
ON (t.ROLE_NAME = s.ROLE_NAME AND t.FROM_STATUS = s.FROM_STATUS AND t.ACTION_CODE = s.ACTION_CODE)
WHEN NOT MATCHED THEN
  INSERT (ROLE_NAME, FROM_STATUS, ACTION_CODE, ENABLED) VALUES (s.ROLE_NAME, s.FROM_STATUS, s.ACTION_CODE, 'Y');

MERGE INTO ROLE_WORKFLOW_ACTION_ACCESS t
USING (SELECT 'FACILITATOR' AS ROLE_NAME, 'UNDER_REVIEW' AS FROM_STATUS, 'REJECT' AS ACTION_CODE FROM dual) s
ON (t.ROLE_NAME = s.ROLE_NAME AND t.FROM_STATUS = s.FROM_STATUS AND t.ACTION_CODE = s.ACTION_CODE)
WHEN NOT MATCHED THEN
  INSERT (ROLE_NAME, FROM_STATUS, ACTION_CODE, ENABLED) VALUES (s.ROLE_NAME, s.FROM_STATUS, s.ACTION_CODE, 'Y');

MERGE INTO ROLE_WORKFLOW_ACTION_ACCESS t
USING (SELECT 'FACILITATOR' AS ROLE_NAME, 'UNDER_REVIEW' AS FROM_STATUS, 'REWORK' AS ACTION_CODE FROM dual) s
ON (t.ROLE_NAME = s.ROLE_NAME AND t.FROM_STATUS = s.FROM_STATUS AND t.ACTION_CODE = s.ACTION_CODE)
WHEN NOT MATCHED THEN
  INSERT (ROLE_NAME, FROM_STATUS, ACTION_CODE, ENABLED) VALUES (s.ROLE_NAME, s.FROM_STATUS, s.ACTION_CODE, 'Y');

MERGE INTO ROLE_WORKFLOW_ACTION_ACCESS t
USING (SELECT 'FACILITATOR' AS ROLE_NAME, 'APPROVED' AS FROM_STATUS, 'CLOSE' AS ACTION_CODE FROM dual) s
ON (t.ROLE_NAME = s.ROLE_NAME AND t.FROM_STATUS = s.FROM_STATUS AND t.ACTION_CODE = s.ACTION_CODE)
WHEN NOT MATCHED THEN
  INSERT (ROLE_NAME, FROM_STATUS, ACTION_CODE, ENABLED) VALUES (s.ROLE_NAME, s.FROM_STATUS, s.ACTION_CODE, 'Y');

MERGE INTO ROLE_WORKFLOW_ACTION_ACCESS t
USING (SELECT 'FACILITATOR' AS ROLE_NAME, 'REJECTED' AS FROM_STATUS, 'CLOSE' AS ACTION_CODE FROM dual) s
ON (t.ROLE_NAME = s.ROLE_NAME AND t.FROM_STATUS = s.FROM_STATUS AND t.ACTION_CODE = s.ACTION_CODE)
WHEN NOT MATCHED THEN
  INSERT (ROLE_NAME, FROM_STATUS, ACTION_CODE, ENABLED) VALUES (s.ROLE_NAME, s.FROM_STATUS, s.ACTION_CODE, 'Y');

/* ============================================================================
   E) Seed ROLE_MODULE_ACCESS (module codes from ModuleCode constants)
   ============================================================================ */
MERGE INTO ROLE_MODULE_ACCESS t
USING (SELECT 'MAKER' AS ROLE, 'UPLOAD' AS MODULE_CODE FROM dual) s
ON (t.ROLE = s.ROLE AND t.MODULE_CODE = s.MODULE_CODE)
WHEN NOT MATCHED THEN
  INSERT (ROLE, MODULE_CODE, ENABLED) VALUES (s.ROLE, s.MODULE_CODE, 'Y');

MERGE INTO ROLE_MODULE_ACCESS t
USING (SELECT 'MAKER' AS ROLE, 'REVIEW' AS MODULE_CODE FROM dual) s
ON (t.ROLE = s.ROLE AND t.MODULE_CODE = s.MODULE_CODE)
WHEN NOT MATCHED THEN
  INSERT (ROLE, MODULE_CODE, ENABLED) VALUES (s.ROLE, s.MODULE_CODE, 'Y');

MERGE INTO ROLE_MODULE_ACCESS t
USING (SELECT 'MAKER' AS ROLE, 'REPORTS' AS MODULE_CODE FROM dual) s
ON (t.ROLE = s.ROLE AND t.MODULE_CODE = s.MODULE_CODE)
WHEN NOT MATCHED THEN
  INSERT (ROLE, MODULE_CODE, ENABLED) VALUES (s.ROLE, s.MODULE_CODE, 'Y');

MERGE INTO ROLE_MODULE_ACCESS t
USING (SELECT 'REVIEWER' AS ROLE, 'REVIEW' AS MODULE_CODE FROM dual) s
ON (t.ROLE = s.ROLE AND t.MODULE_CODE = s.MODULE_CODE)
WHEN NOT MATCHED THEN
  INSERT (ROLE, MODULE_CODE, ENABLED) VALUES (s.ROLE, s.MODULE_CODE, 'Y');

MERGE INTO ROLE_MODULE_ACCESS t
USING (SELECT 'REVIEWER' AS ROLE, 'UPLOAD' AS MODULE_CODE FROM dual) s
ON (t.ROLE = s.ROLE AND t.MODULE_CODE = s.MODULE_CODE)
WHEN NOT MATCHED THEN
  INSERT (ROLE, MODULE_CODE, ENABLED) VALUES (s.ROLE, s.MODULE_CODE, 'Y');

MERGE INTO ROLE_MODULE_ACCESS t
USING (SELECT 'REVIEWER' AS ROLE, 'AUDIT' AS MODULE_CODE FROM dual) s
ON (t.ROLE = s.ROLE AND t.MODULE_CODE = s.MODULE_CODE)
WHEN NOT MATCHED THEN
  INSERT (ROLE, MODULE_CODE, ENABLED) VALUES (s.ROLE, s.MODULE_CODE, 'Y');

MERGE INTO ROLE_MODULE_ACCESS t
USING (SELECT 'APPROVER' AS ROLE, 'REVIEW' AS MODULE_CODE FROM dual) s
ON (t.ROLE = s.ROLE AND t.MODULE_CODE = s.MODULE_CODE)
WHEN NOT MATCHED THEN
  INSERT (ROLE, MODULE_CODE, ENABLED) VALUES (s.ROLE, s.MODULE_CODE, 'Y');

MERGE INTO ROLE_MODULE_ACCESS t
USING (SELECT 'APPROVER' AS ROLE, 'AUDIT' AS MODULE_CODE FROM dual) s
ON (t.ROLE = s.ROLE AND t.MODULE_CODE = s.MODULE_CODE)
WHEN NOT MATCHED THEN
  INSERT (ROLE, MODULE_CODE, ENABLED) VALUES (s.ROLE, s.MODULE_CODE, 'Y');

MERGE INTO ROLE_MODULE_ACCESS t
USING (SELECT 'APPROVER' AS ROLE, 'FAST_TRACK_APPROVAL' AS MODULE_CODE FROM dual) s
ON (t.ROLE = s.ROLE AND t.MODULE_CODE = s.MODULE_CODE)
WHEN NOT MATCHED THEN
  INSERT (ROLE, MODULE_CODE, ENABLED) VALUES (s.ROLE, s.MODULE_CODE, 'Y');

MERGE INTO ROLE_MODULE_ACCESS t
USING (SELECT 'FACILITATOR' AS ROLE, 'UPLOAD' AS MODULE_CODE FROM dual) s
ON (t.ROLE = s.ROLE AND t.MODULE_CODE = s.MODULE_CODE)
WHEN NOT MATCHED THEN
  INSERT (ROLE, MODULE_CODE, ENABLED) VALUES (s.ROLE, s.MODULE_CODE, 'Y');

MERGE INTO ROLE_MODULE_ACCESS t
USING (SELECT 'FACILITATOR' AS ROLE, 'REVIEW' AS MODULE_CODE FROM dual) s
ON (t.ROLE = s.ROLE AND t.MODULE_CODE = s.MODULE_CODE)
WHEN NOT MATCHED THEN
  INSERT (ROLE, MODULE_CODE, ENABLED) VALUES (s.ROLE, s.MODULE_CODE, 'Y');

MERGE INTO ROLE_MODULE_ACCESS t
USING (SELECT 'FACILITATOR' AS ROLE, 'AUDIT' AS MODULE_CODE FROM dual) s
ON (t.ROLE = s.ROLE AND t.MODULE_CODE = s.MODULE_CODE)
WHEN NOT MATCHED THEN
  INSERT (ROLE, MODULE_CODE, ENABLED) VALUES (s.ROLE, s.MODULE_CODE, 'Y');

MERGE INTO ROLE_MODULE_ACCESS t
USING (SELECT 'FACILITATOR' AS ROLE, 'REPORTS' AS MODULE_CODE FROM dual) s
ON (t.ROLE = s.ROLE AND t.MODULE_CODE = s.MODULE_CODE)
WHEN NOT MATCHED THEN
  INSERT (ROLE, MODULE_CODE, ENABLED) VALUES (s.ROLE, s.MODULE_CODE, 'Y');

/* ============================================================================
   F) Sample/dev-only user-role mappings (comment out if not needed)
   ============================================================================ */
-- MERGE INTO USER_ROLE_MAP t
-- USING (SELECT 'samson' AS USER_ID, 'FACILITATOR' AS ROLE_NAME FROM dual) s
-- ON (t.USER_ID = s.USER_ID AND t.ROLE_NAME = s.ROLE_NAME)
-- WHEN NOT MATCHED THEN
--   INSERT (USER_ID, ROLE_NAME, ENABLED) VALUES (s.USER_ID, s.ROLE_NAME, 'Y');
--
-- MERGE INTO USER_ROLE_MAP t
-- USING (SELECT 'dev-user' AS USER_ID, 'FACILITATOR' AS ROLE_NAME FROM dual) s
-- ON (t.USER_ID = s.USER_ID AND t.ROLE_NAME = s.ROLE_NAME)
-- WHEN NOT MATCHED THEN
--   INSERT (USER_ID, ROLE_NAME, ENABLED) VALUES (s.USER_ID, s.ROLE_NAME, 'Y');
